alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
alias glg='git log --graph --decorate'
alias g='git'
alias jsh='find app/assets/javascripts -name "*.js" -exec jshint {} \;'
alias rt='rake test'
alias rtc='TESTOPTS="--fail-fast" rake test && rubocop'
alias dbreload='bundle exec rake db:drop; bundle exec db:create; bundle exec rake db:migrate; bundle exec rake db:fixtures:load'
alias bi='bundle install'
alias guard='rvm 2.3.0 do guard'
alias stp='pushd ~/property; script/start; popd'
alias spp='pushd ~/property; script/stop; popd'
alias brake='bundle exec rake'
alias rtest='ruby -Itest'
alias ret='RAILS_ENV=test'
alias hgrep='history | grep'
